name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install 🔧
        run: npm install

      - name: Build 🔧
        run: |
          npm build:production
          touch out/.nojekyll
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: production # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
